version: '3.7'

services:
  appserver:
    stdin_open: true
    tty: true
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    env_file:
      - .env.dev
  database:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

volumes:
  postgres_data: