version: '3.7'

services:
  project:
    build:
      context: .
      dockerfile: project/Dockerfile # the dir here instead of in context allows for `COPY .env .env` in the Dockerfile
      target: ${APP_TARGET}
      args:
        postgres_version: ${POSTGRES_VERSION}
    restart: always
    volumes:
      - .:/usr/src
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database
    environment:
      COMPOSE_LOCAL_PWD: $PWD
  database:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:delegated
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${DATABASE_POSTGRES_SUPERPASS}
      POSTGRES_DB: ${DATABASE_POSTGRES_DB_NAME}
      COMPOSE_LOCAL_PWD: $PWD
  node:
    image: node:${NODE_VERSION}
    restart: 'no'
    command: /bin/true # only run the container when you need it
    volumes:
      - .:/usr/src
    env_file:
      - .env
    ports:
      - 3000:3000
      - 3001:3001
      - 8000:8001

volumes:
  postgres_data: