version: '3.7'

services:
  project:
    tty: true
    build:
      context: project
      dockerfile: Dockerfile-${APP_VERSION}
      target: ${APP_TARGET}
      args:
        postgres_version: ${POSTGRES_VERSION}
        node_version: ${NODE_VERSION}
    restart: always
    volumes:
      - .:/usr/src
      - ~/.ssh:/usr/local/machine/.ssh
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database
    environment:
      COMPOSE_LOCAL_PWD: $PWD
  database:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:delegated
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${DATABASE_POSTGRES_SUPERPASS}
      POSTGRES_DB: ${DATABASE_POSTGRES_DB_NAME}
      COMPOSE_LOCAL_PWD: $PWD

volumes:
  postgres_data: