version: '3.7'

services:
  app:
    stdin_open: true
    tty: true
    build:
      context: ./app
      dockerfile: Dockerfile-${APP_VERSION}
      target: ${APP_TARGET}
    restart: always
    volumes:
      - .:/usr/src
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: postgres:12
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:delegated
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${DATABASE_POSTGRES_SUPERPASS}
      POSTGRES_DB: ${DATABASE_POSTGRES_SCHEMA_NAME}


volumes:
  postgres_data: